/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tetris.GUI;



import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author berna
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcerca = new javax.swing.JButton();
        btnRegras = new javax.swing.JButton();
        bntJogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnAcerca.setText("Acerca de");
        btnAcerca.setAlignmentX(0.5F);
        btnAcerca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnAcercaComponentShown(evt);
            }
        });
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcerca);
        btnAcerca.setBounds(170, 160, 120, 35);

        btnRegras.setText("Regras do jogo");
        btnRegras.setAlignmentX(0.5F);
        btnRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegras);
        btnRegras.setBounds(170, 210, 120, 35);

        bntJogar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bntJogar.setText("Play");
        bntJogar.setAlignmentX(0.5F);
        bntJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntJogarActionPerformed(evt);
            }
        });
        getContentPane().add(bntJogar);
        bntJogar.setBounds(140, 300, 170, 70);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 65)); // NOI18N
        jLabel1.setText("Tetris");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 270, 100);

        jLabel2.setText("ver 0.0.3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 440, 50, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntJogarActionPerformed
        Tetris objTetris = new Tetris();
        objTetris.setVisible(true);
    }//GEN-LAST:event_bntJogarActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        Acerca objAcerca = new Acerca();
        objAcerca.setVisible(true);
       
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegrasActionPerformed
        RegrasJogo objRegras = new RegrasJogo();
        objRegras.setVisible(true);
    }//GEN-LAST:event_btnRegrasActionPerformed

    private void btnAcercaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnAcercaComponentShown
        Acerca objAcerca = new Acerca();
        objAcerca.setVisible(true);
         
    }//GEN-LAST:event_btnAcercaComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntJogar;
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnRegras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
